apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxbiq5331-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxbiq5331-tenant-component
    app.kubernetes.io/part-of: loadxbiq5331-tenant-app
  name: loadxbiq5331-tenant-component
  namespace: loadxbiq5331-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxbiq5331-tenant-component
    weight: null
status: {}
